=== Azure/azureml-assets/assets/batch_score/components/driver/src/batch_score/common/configuration/schemas/configuration.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "required": [
        "api",
        "authentication",
        "inference_endpoint"
    ],
    "unevaluatedProperties": false,
    "properties": {
        "api": {
            "description": "The API to use for scoring.",
            "oneOf": [
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/api/completion.json"
                },
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/api/chat_completion.json"
                },
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/api/embedding.json"
                }
            ]
        },
        "authentication": {
            "description": "Specifies how to authenticate scoring requests.",
            "oneOf": [
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/authentication/connection.json"
                },
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/authentication/managed_identity.json"
                }
            ]
        },
        "concurrency_settings": {
            "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/concurrency_settings.json",
            "default": {}
        },
        "inference_endpoint": {
            "oneOf": [
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/inference_endpoint/azure_openai.json"
                },
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/inference_endpoint/azureml_online_endpoint.json"
                },
                {
                    "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/inference_endpoint/azureml_serverless_endpoint.json"
                }
            ]
        },
        "request_settings": {
            "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/request_settings.json",
            "default": {}
        },
        "log_settings": {
            "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/log_settings.json",
            "default": {}
        },
        "output_settings": {
            "$ref": "file:///driver/src/batch_score/common/configuration/file/schemas/public/output_settings.json",
            "default": {}
        }
    }
}

=== Azure/azureml-assets/assets/batch_score_oss/components/driver/test_assets/configuration_files/valid/concurrency_settings.json
{
    "api": {
        "type": "completion"
    },
    "authentication": {
        "type": "managed_identity"
    },
    "concurrency_settings": {
        "initial_worker_count": 20,
        "max_worker_count": 100
    },
    "inference_endpoint": {
        "type": "azure_openai",
        "url": "https://sunjoli-aoai.openai.azure.com/openai/deployments/turbo/completions?api-version=2023-03-15-preview"
    }
}

=== Azure/azureml-assets/assets/batch_score/components/driver/test_assets/configuration_files/for_e2e_tests/mir_with_connection.json
{
    "api": {
        "type": "completion",
        "response_segment_size": 1000
    },
    "authentication": {
        "type": "connection",
        "name": "ClipModelConnection"
    },
    "inference_endpoint": {
        "type": "azureml_online_endpoint",
        "url": "https://mir-clip-endpoint.centralus.inference.ml.azure.com/score"
    },
    "request_settings":{
        "headers":{
            "azureml-model-deployment": "openai-clip-vit-base-patch32-5"
        }
    }
}

=== Azure/azureml-assets/assets/batch_score_oss/components/driver/test_assets/configuration_files/valid/output_settings.json
{
    "api": {
        "type": "completion"
    },
    "authentication": {
        "type": "managed_identity"
    },
    "inference_endpoint": {
        "type": "azure_openai",
        "url": "https://sunjoli-aoai.openai.azure.com/openai/deployments/turbo/completions?api-version=2023-03-15-preview"
    },
    "output_settings": {
        "ensure_ascii": true,
        "save_partitioned_scoring_results": true
    }
}

=== Azure/azureml-assets/assets/batch_score/components/driver/test_assets/configuration_files/valid/log_settings.json
{
    "api": {
        "type": "completion"
    },
    "authentication": {
        "type": "managed_identity"
    },
    "inference_endpoint": {
        "type": "azure_openai",
        "url": "https://sunjoli-aoai.openai.azure.com/openai/deployments/turbo/completions?api-version=2023-03-15-preview"
    },
    "log_settings": {
        "app_insights_connection_string": "InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://westus2-2.ingest.ai.applicationinsights.io/",
        "app_insights_log_level": "debug",
        "stdout_log_level": "info"
    }
}

=== Azure/azureml-assets/assets/batch_score/components/driver/test_assets/configuration_files/valid/request_settings.json
{
    "api": {
        "type": "completion"
    },
    "authentication": {
        "type": "managed_identity"
    },
    "inference_endpoint": {
        "type": "azure_openai",
        "url": "https://sunjoli-aoai.openai.azure.com/openai/deployments/turbo/completions?api-version=2023-03-15-preview"
    },
    "request_settings": {
        "headers": {
            "custom_header": "header_value"
        },
        "properties": {
            "custom_property": "property_value",
            "custom_property_2": "property_value_2"
        },
        "timeout": 300,
        "user_agent_identifier": "some identifier"
    }
}
